### Register

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name":"giang",
    "password":"123",
    "phone":"0379245168",
    "role": "AGENT"
}

###
POST http://localhost:5000/api/propertyType
Content-Type: application/json


{
    "name":"Houees",
    "image":"dfgdgdg",
    "description":"0379245168",
}


### SignIn
POST http://localhost:5000/api/auth/signin
Content-Type: application/json

{

    "password":"123",
    "phone":"0379245168"
}
